version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: smarteats-mongo-prod
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: smarteats
    volumes:
      - mongodb_data:/data/db
      - ./backend/scripts/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    networks:
      - smarteats-network
    # Don't expose port in production - only internal access

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    container_name: smarteats-backend-prod
    restart: unless-stopped
    environment:
      NODE_ENV: production
      MONGO_URI: mongodb://${MONGO_ROOT_USERNAME}:${MONGO_ROOT_PASSWORD}@mongodb:27017/smarteats?authSource=admin
    env_file:
      - ./backend/.env.prod
    depends_on:
      - mongodb
    networks:
      - smarteats-network
    # Don't expose port - will be accessed through nginx

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: production
    container_name: smarteats-frontend-prod
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
    depends_on:
      - backend
    networks:
      - smarteats-network

volumes:
  mongodb_data:


networks:
  smarteats-network:
    driver: bridge
